import type { Question } from "../types";

export const advancedQuestions: Question[] = [
  {
    id: "adv-01",
    level: "advanced",
    topic: "window-functions",
    topicLabel: "ROW_NUMBER",
    difficulty: "medium",
    title: "Number employees within each department by salary",
    description: "For each employee, show employee_id, dept_id, salary, and a row number (1 = highest paid) within their department, ordered by salary descending.",
    dataset: "company",
    tables: ["employees"],
    hints: [
      "ROW_NUMBER() OVER (...) assigns a unique sequential number.",
      "PARTITION BY resets the numbering for each department; ORDER BY controls the ranking order.",
      "ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rn",
    ],
    solution:
      "SELECT employee_id, dept_id, salary, ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rn FROM employees;",
    explanation: "PARTITION BY dept_id restarts the ROW_NUMBER count at 1 for every department; ORDER BY salary DESC ranks highest-paid first.",
    thoughtProcess: [
      "\"Within each department\" → PARTITION BY dept_id.",
      "\"1 = highest paid\" → ORDER BY salary DESC inside the OVER clause.",
    ],
    concept: "ROW_NUMBER + PARTITION BY",
    tags: ["row-number", "partition-by", "window-functions"],
    requiresPattern: { regex: "ROW_NUMBER\\s*\\(", message: "Use the ROW_NUMBER() window function." },
  },
  {
    id: "adv-02",
    level: "advanced",
    topic: "window-functions",
    topicLabel: "Second highest salary per department",
    difficulty: "hard",
    title: "Second highest salary in each department",
    description: "Find the second-highest salary in each department. Return dept_id and salary. If a department has fewer than 2 employees, it should not appear.",
    dataset: "company",
    tables: ["employees"],
    hints: [
      "DENSE_RANK() handles ties better than ROW_NUMBER for 'Nth highest' problems.",
      "Rank salaries within each department, then filter for rank = 2 in an outer query or CTE.",
      "WITH ranked AS (SELECT dept_id, salary, DENSE_RANK() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rnk FROM employees) SELECT dept_id, salary FROM ranked WHERE rnk = 2;",
    ],
    solution:
      "WITH ranked AS (SELECT dept_id, salary, DENSE_RANK() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rnk FROM employees) SELECT DISTINCT dept_id, salary FROM ranked WHERE rnk = 2;",
    explanation: "DENSE_RANK gives tied salaries the same rank without skipping numbers, so 'the 2nd highest' correctly means the second distinct salary level.",
    thoughtProcess: [
      "\"Second highest\" → rank salaries per department, then take rnk = 2.",
      "Window functions can't be filtered directly in WHERE, so wrap them in a CTE first.",
    ],
    concept: "DENSE_RANK for Nth-highest problems",
    tags: ["dense-rank", "nth-highest", "cte"],
    requiresPattern: { regex: "DENSE_RANK\\s*\\(", message: "Use DENSE_RANK() to handle salary ties correctly." },
  },
  {
    id: "adv-03",
    level: "advanced",
    topic: "window-functions",
    topicLabel: "Top 3 per department",
    difficulty: "hard",
    title: "Top 3 highest-paid employees per department",
    description: "Return the top 3 highest-paid employees in each department (by salary). Include dept_id, employee_id, salary, and the rank.",
    dataset: "company",
    tables: ["employees"],
    hints: [
      "This is the classic 'Top-N per group' pattern.",
      "Rank within each department using RANK() or DENSE_RANK(), then keep rank <= 3.",
      "WITH ranked AS (SELECT *, RANK() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rnk FROM employees) SELECT dept_id, employee_id, salary, rnk FROM ranked WHERE rnk <= 3;",
    ],
    solution:
      "WITH ranked AS (SELECT dept_id, employee_id, salary, RANK() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rnk FROM employees) SELECT dept_id, employee_id, salary, rnk FROM ranked WHERE rnk <= 3;",
    explanation: "Top-N-per-group is solved by ranking within a PARTITION and filtering the rank in an outer query.",
    thoughtProcess: ["\"Top 3 per department\" → PARTITION BY dept_id, then WHERE rank <= 3."],
    concept: "Top-N per group",
    tags: ["rank", "top-n", "partition-by"],
  },
  {
    id: "adv-04",
    level: "advanced",
    topic: "window-functions",
    topicLabel: "Highest paid employee per department",
    difficulty: "medium",
    title: "The highest-paid employee in each department",
    description: "Return the single highest-paid employee in each department: dept_id, employee_id, first_name, last_name, salary.",
    dataset: "company",
    tables: ["employees"],
    hints: [
      "This is Top-N per group with N = 1.",
      "Use ROW_NUMBER (or RANK) partitioned by department, ordered by salary descending, and keep rank 1.",
      "WITH ranked AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rn FROM employees) SELECT dept_id, employee_id, first_name, last_name, salary FROM ranked WHERE rn = 1;",
    ],
    solution:
      "WITH ranked AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rn FROM employees) SELECT dept_id, employee_id, first_name, last_name, salary FROM ranked WHERE rn = 1;",
    explanation: "ROW_NUMBER guarantees exactly one row per partition even if two employees are tied for the top salary.",
    thoughtProcess: ["Single winner per group → ROW_NUMBER, rn = 1."],
    concept: "Top-1 per group",
    tags: ["row-number", "top-n"],
  },
  {
    id: "adv-05",
    level: "advanced",
    topic: "window-functions",
    topicLabel: "Running total",
    difficulty: "medium",
    title: "Running total of order revenue by date",
    description: "For each order, show order_date, total, and a running total of `total` ordered by order_date (earliest first).",
    dataset: "ecommerce",
    tables: ["orders"],
    hints: [
      "A running total is a SUM() window function with an ORDER BY inside OVER.",
      "By default, SUM(...) OVER (ORDER BY x) accumulates from the first row up to the current row.",
      "SELECT order_date, total, SUM(total) OVER (ORDER BY order_date) AS running_total FROM orders;",
    ],
    solution: "SELECT order_date, total, SUM(total) OVER (ORDER BY order_date, id) AS running_total FROM orders ORDER BY order_date, id;",
    explanation: "SUM() OVER (ORDER BY ...) without a PARTITION BY accumulates across the entire result set in the given order.",
    thoughtProcess: ["\"Running total ... ordered by date\" → SUM() OVER (ORDER BY order_date)."],
    concept: "Running totals with window functions",
    tags: ["running-total", "window-functions"],
    orderMatters: true,
    requiresPattern: { regex: "OVER\\s*\\(", message: "Use a window function (SUM(...) OVER (...))." },
  },
  {
    id: "adv-06",
    level: "advanced",
    topic: "window-functions",
    topicLabel: "LAG",
    difficulty: "medium",
    title: "Compare each admission to the patient's previous one",
    description:
      "For each admission, show patient_id, admission_date, and the patient's previous admission_date (NULL if it's their first), ordered by patient then date.",
    dataset: "healthcare",
    tables: ["admissions"],
    hints: [
      "LAG(column) OVER (...) looks at the previous row within a window.",
      "Partition by patient_id so 'previous' means the previous admission for the same patient.",
      "LAG(admission_date) OVER (PARTITION BY patient_id ORDER BY admission_date) AS prev_admission_date",
    ],
    solution:
      "SELECT patient_id, admission_date, LAG(admission_date) OVER (PARTITION BY patient_id ORDER BY admission_date) AS prev_admission_date FROM admissions ORDER BY patient_id, admission_date;",
    explanation: "LAG() reaches back to a prior row in the same partition; the first row in each partition has no prior row, so LAG returns NULL.",
    thoughtProcess: ["\"Previous admission for the same patient\" → LAG partitioned by patient_id, ordered by date."],
    concept: "LAG window function",
    tags: ["lag", "window-functions"],
    orderMatters: true,
    requiresPattern: { regex: "LAG\\s*\\(", message: "Use the LAG() window function." },
  },
  {
    id: "adv-07",
    level: "advanced",
    topic: "window-functions",
    topicLabel: "LEAD",
    difficulty: "medium",
    title: "Next order date per customer",
    description: "For each order, show customer_id, order_date, and the date of that customer's next order (NULL if there isn't one), ordered by customer then date.",
    dataset: "ecommerce",
    tables: ["orders"],
    hints: [
      "LEAD(column) OVER (...) looks ahead to the following row within a window.",
      "Partition by customer_id, order by order_date.",
      "LEAD(order_date) OVER (PARTITION BY customer_id ORDER BY order_date) AS next_order_date",
    ],
    solution:
      "SELECT customer_id, order_date, LEAD(order_date) OVER (PARTITION BY customer_id ORDER BY order_date) AS next_order_date FROM orders ORDER BY customer_id, order_date;",
    explanation: "LEAD() is the mirror image of LAG() — it looks forward to the next row in the partition instead of backward.",
    thoughtProcess: ["\"Next order for the same customer\" → LEAD partitioned by customer_id."],
    concept: "LEAD window function",
    tags: ["lead", "window-functions"],
    orderMatters: true,
    requiresPattern: { regex: "LEAD\\s*\\(", message: "Use the LEAD() window function." },
  },
  {
    id: "adv-08",
    level: "advanced",
    topic: "window-functions",
    topicLabel: "FIRST_VALUE",
    difficulty: "medium",
    title: "Each employee vs. their department's top salary",
    description: "For every employee, show employee_id, dept_id, salary, and the highest salary in their department (using FIRST_VALUE).",
    dataset: "company",
    tables: ["employees"],
    hints: [
      "FIRST_VALUE(column) OVER (...) returns the first value in the ordered window frame.",
      "Order by salary descending so the 'first' value is the maximum.",
      "FIRST_VALUE(salary) OVER (PARTITION BY dept_id ORDER BY salary DESC) AS dept_top_salary",
    ],
    solution:
      "SELECT employee_id, dept_id, salary, FIRST_VALUE(salary) OVER (PARTITION BY dept_id ORDER BY salary DESC) AS dept_top_salary FROM employees;",
    explanation: "FIRST_VALUE grabs the value from the first row of the ordered frame — with DESC ordering, that's the maximum.",
    thoughtProcess: ["\"Top salary in department, shown on every row\" → FIRST_VALUE partitioned by dept_id."],
    concept: "FIRST_VALUE window function",
    tags: ["first-value", "window-functions"],
    requiresPattern: { regex: "FIRST_VALUE\\s*\\(", message: "Use the FIRST_VALUE() window function." },
  },
  {
    id: "adv-09",
    level: "advanced",
    topic: "cte",
    topicLabel: "Recursive CTE",
    difficulty: "expert",
    title: "Full management chain above each employee",
    description:
      "Using a recursive CTE, list every (employee_id, manager_id) pair showing each employee alongside ALL of their managers up the chain (not just their direct manager).",
    dataset: "company",
    tables: ["employees"],
    hints: [
      "A recursive CTE has an anchor (base case) and a recursive part joined with UNION ALL.",
      "Anchor: each employee's direct manager. Recursive step: join the CTE back to employees on manager_id to climb one level higher each time.",
      "WITH RECURSIVE chain AS (SELECT employee_id, manager_id FROM employees WHERE manager_id IS NOT NULL UNION ALL SELECT c.employee_id, e.manager_id FROM chain c JOIN employees e ON c.manager_id = e.employee_id WHERE e.manager_id IS NOT NULL) SELECT * FROM chain;",
    ],
    solution:
      "WITH RECURSIVE chain AS (SELECT employee_id, manager_id FROM employees WHERE manager_id IS NOT NULL UNION ALL SELECT c.employee_id, e.manager_id FROM chain c JOIN employees e ON c.manager_id = e.employee_id WHERE e.manager_id IS NOT NULL) SELECT employee_id, manager_id FROM chain;",
    explanation: "The recursive part keeps joining back to employees, climbing the manager chain one level at a time, until it reaches someone with no manager.",
    thoughtProcess: [
      "Hierarchical, unknown depth → recursive CTE.",
      "Anchor is the direct manager relationship; the recursive step follows manager_id one more level each pass.",
    ],
    concept: "Recursive CTEs",
    tags: ["recursive-cte", "hierarchy"],
    requiresPattern: { regex: "WITH\\s+RECURSIVE", message: "Use WITH RECURSIVE to build the management chain." },
  },
  {
    id: "adv-10",
    level: "advanced",
    topic: "self-join",
    topicLabel: "Self join",
    difficulty: "medium",
    title: "Employees who earn more than their manager",
    description: "Using a self-join, find employees whose salary is greater than their manager's salary. Show the employee's name, their salary, and their manager's name and salary.",
    dataset: "company",
    tables: ["employees"],
    hints: [
      "Join the employees table to itself: once as the employee, once as the manager.",
      "The join condition links e.manager_id to m.employee_id.",
      "SELECT e.first_name, e.salary, m.first_name AS mgr_name, m.salary AS mgr_salary FROM employees e JOIN employees m ON e.manager_id = m.employee_id WHERE e.salary > m.salary;",
    ],
    solution:
      "SELECT e.employee_id, e.first_name AS employee_name, e.salary AS employee_salary, m.first_name AS manager_name, m.salary AS manager_salary FROM employees e JOIN employees m ON e.manager_id = m.employee_id WHERE e.salary > m.salary;",
    explanation: "A self-join treats the same table as two logical roles (employee and manager) via two aliases, letting you compare rows to related rows in the same table.",
    thoughtProcess: ["Comparing rows within the same table by a relationship (manager_id) → self join with two aliases."],
    concept: "Self joins",
    tags: ["self-join"],
  },
  {
    id: "adv-11",
    level: "advanced",
    topic: "aggregation",
    topicLabel: "Departments above company average",
    difficulty: "hard",
    title: "Departments whose average salary beats the company average",
    description: "Find departments whose average salary is greater than the overall company average salary. Return dept_id and the department's average salary.",
    dataset: "company",
    tables: ["employees"],
    hints: [
      "You need two levels of aggregation: overall average, and per-department average.",
      "Compute the company-wide average in a subquery, then compare it to each department's average in HAVING.",
      "SELECT dept_id, AVG(salary) FROM employees GROUP BY dept_id HAVING AVG(salary) > (SELECT AVG(salary) FROM employees);",
    ],
    solution:
      "SELECT dept_id, AVG(salary) AS dept_avg_salary FROM employees GROUP BY dept_id HAVING AVG(salary) > (SELECT AVG(salary) FROM employees);",
    explanation: "The scalar subquery computes one company-wide number once; HAVING then compares each department's aggregate against it.",
    thoughtProcess: ["Comparing a group aggregate to a global aggregate → scalar subquery inside HAVING."],
    concept: "Multi-level aggregation",
    tags: ["aggregation", "having", "subquery"],
  },
  {
    id: "adv-12",
    level: "advanced",
    topic: "duplicates",
    topicLabel: "Duplicate detection",
    difficulty: "medium",
    title: "Employees sharing the same email",
    description: "Find email addresses used by more than one employee, along with how many employees share it.",
    dataset: "company",
    tables: ["employees"],
    hints: [
      "Group by the column you're checking for duplicates.",
      "HAVING COUNT(*) > 1 keeps only values that repeat.",
      "SELECT email, COUNT(*) FROM employees GROUP BY email HAVING COUNT(*) > 1;",
    ],
    solution: "SELECT email, COUNT(*) AS times_used FROM employees GROUP BY email HAVING COUNT(*) > 1;",
    explanation: "Duplicate detection is a GROUP BY + HAVING COUNT(*) > 1 pattern applied to the column you care about.",
    thoughtProcess: ["\"Shared by more than one\" → GROUP BY email, HAVING COUNT(*) > 1."],
    concept: "Duplicate detection",
    tags: ["duplicates", "having"],
  },
  {
    id: "adv-13",
    level: "advanced",
    topic: "gaps-and-islands",
    topicLabel: "Gaps and islands",
    difficulty: "expert",
    title: "Consecutive-day admission streaks per patient",
    description:
      "For patient_id 1, list each admission_date grouped into 'islands' of consecutive calendar days (admission_date minus a running row number, grouped). Return the island's start date, end date, and number of admissions in it.",
    dataset: "healthcare",
    tables: ["admissions"],
    hints: [
      "This is the classic 'gaps and islands' pattern: subtract a ROW_NUMBER (in days) from the date — consecutive dates produce the same difference.",
      "Group by that difference to find each island's boundaries.",
      "WITH numbered AS (SELECT admission_date, ROW_NUMBER() OVER (ORDER BY admission_date) AS rn FROM admissions WHERE patient_id = 1), islands AS (SELECT admission_date, admission_date - rn * INTERVAL 1 DAY AS grp FROM numbered) SELECT MIN(admission_date), MAX(admission_date), COUNT(*) FROM islands GROUP BY grp;",
    ],
    solution:
      "WITH numbered AS (SELECT admission_date, ROW_NUMBER() OVER (ORDER BY admission_date) AS rn FROM admissions WHERE patient_id = 1), islands AS (SELECT admission_date, admission_date - rn * INTERVAL 1 DAY AS grp FROM numbered) SELECT MIN(admission_date) AS island_start, MAX(admission_date) AS island_end, COUNT(*) AS admissions_in_island FROM islands GROUP BY grp;",
    explanation: "Subtracting a sequential row number (in days) from a date is constant for any run of consecutive days, which turns 'find consecutive runs' into an ordinary GROUP BY.",
    thoughtProcess: [
      "Consecutive-run detection is the 'gaps and islands' problem.",
      "ROW_NUMBER() minus the date value is identical for every row inside one unbroken run.",
    ],
    concept: "Gaps and islands",
    tags: ["gaps-and-islands", "window-functions"],
  },
  {
    id: "adv-14",
    level: "advanced",
    topic: "conditional-aggregation",
    topicLabel: "Conditional aggregation",
    difficulty: "medium",
    title: "Order counts by status, pivoted per customer",
    description:
      "For each customer, show how many of their orders are 'delivered' and how many are 'cancelled', as two separate columns (delivered_count, cancelled_count).",
    dataset: "ecommerce",
    tables: ["orders"],
    hints: [
      "Conditional aggregation combines CASE WHEN with an aggregate like SUM or COUNT.",
      "SUM(CASE WHEN status = 'delivered' THEN 1 ELSE 0 END) counts only matching rows.",
      "SELECT customer_id, SUM(CASE WHEN status='delivered' THEN 1 ELSE 0 END), SUM(CASE WHEN status='cancelled' THEN 1 ELSE 0 END) FROM orders GROUP BY customer_id;",
    ],
    solution:
      "SELECT customer_id, SUM(CASE WHEN status = 'delivered' THEN 1 ELSE 0 END) AS delivered_count, SUM(CASE WHEN status = 'cancelled' THEN 1 ELSE 0 END) AS cancelled_count FROM orders GROUP BY customer_id;",
    explanation: "Wrapping a CASE expression inside SUM() lets one aggregation pass produce several conditional counts side by side — a manual pivot.",
    thoughtProcess: ["Multiple conditional counts as separate columns → SUM(CASE WHEN ...) per condition."],
    concept: "Conditional aggregation",
    tags: ["conditional-aggregation", "case"],
    requiresPattern: { regex: "CASE\\s+WHEN", message: "Use SUM(CASE WHEN ...) conditional aggregation." },
  },
  {
    id: "adv-15",
    level: "advanced",
    topic: "window-functions",
    topicLabel: "Moving average",
    difficulty: "hard",
    title: "3-order moving average of order totals per customer",
    description:
      "For each order, show customer_id, order_date, total, and the moving average of `total` over that order and the 2 preceding orders for the same customer (ordered by order_date).",
    dataset: "ecommerce",
    tables: ["orders"],
    hints: [
      "A moving average needs an explicit frame: ROWS BETWEEN 2 PRECEDING AND CURRENT ROW.",
      "Partition by customer, order by date, and average `total` over that frame.",
      "AVG(total) OVER (PARTITION BY customer_id ORDER BY order_date ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)",
    ],
    solution:
      "SELECT customer_id, order_date, total, AVG(total) OVER (PARTITION BY customer_id ORDER BY order_date ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS moving_avg_3 FROM orders ORDER BY customer_id, order_date;",
    explanation: "ROWS BETWEEN 2 PRECEDING AND CURRENT ROW defines a sliding 3-row frame; AVG() is recomputed for that frame at every row.",
    thoughtProcess: ["\"Moving average over a fixed window of rows\" → explicit ROWS BETWEEN frame on AVG() OVER (...)."],
    concept: "Moving averages with window frames",
    tags: ["moving-average", "window-functions"],
    orderMatters: true,
    requiresPattern: { regex: "ROWS\\s+BETWEEN", message: "Use an explicit ROWS BETWEEN ... window frame." },
  },
  {
    id: "adv-16",
    level: "advanced",
    topic: "window-functions",
    topicLabel: "RANK vs DENSE_RANK",
    difficulty: "medium",
    title: "Rank products by price within category",
    description:
      "For each product, show category_id, name, price, its RANK() and DENSE_RANK() within the category ordered by price descending, so ties and rank-skipping can be compared.",
    dataset: "ecommerce",
    tables: ["products"],
    hints: [
      "RANK() skips numbers after a tie (1,1,3); DENSE_RANK() does not (1,1,2).",
      "Both are partitioned and ordered the same way here.",
      "RANK() OVER (PARTITION BY category_id ORDER BY price DESC) and DENSE_RANK() OVER (PARTITION BY category_id ORDER BY price DESC)",
    ],
    solution:
      "SELECT category_id, name, price, RANK() OVER (PARTITION BY category_id ORDER BY price DESC) AS rnk, DENSE_RANK() OVER (PARTITION BY category_id ORDER BY price DESC) AS dense_rnk FROM products;",
    explanation: "RANK() leaves gaps in the numbering after ties (since it counts all preceding rows), while DENSE_RANK() always increments by exactly 1 between distinct values.",
    thoughtProcess: ["Asked to compare both ranking functions side-by-side → compute both in the same SELECT."],
    concept: "RANK vs DENSE_RANK",
    tags: ["rank", "dense-rank", "window-functions"],
  },
];
