import type { Question } from "../types";

export const beginnerQuestions: Question[] = [
  {
    id: "beg-01",
    level: "beginner",
    topic: "select",
    topicLabel: "SELECT",
    difficulty: "beginner",
    title: "List all patients",
    description: "Write a query that returns the first name and last name of every patient in the `patients` table.",
    dataset: "healthcare",
    tables: ["patients"],
    hints: [
      "Use SELECT followed by the column names you want.",
      "You need first_name and last_name.",
      "SELECT first_name, last_name FROM patients;",
    ],
    solution: "SELECT first_name, last_name FROM patients;",
    explanation: "SELECT picks which columns to return; listing patients requires no filtering at all.",
    thoughtProcess: [
      "\"List all patients\" → no WHERE clause needed, we want every row.",
      "Only two columns are asked for, so name them explicitly rather than using *.",
    ],
    concept: "Basic SELECT",
    tags: ["select"],
  },
  {
    id: "beg-02",
    level: "beginner",
    topic: "distinct",
    topicLabel: "DISTINCT",
    difficulty: "beginner",
    title: "Unique patient cities",
    description: "Show the list of distinct cities in which patients live.",
    dataset: "healthcare",
    tables: ["patients"],
    hints: [
      "Regular SELECT would repeat a city once per patient living there.",
      "DISTINCT removes duplicate rows from the result.",
      "SELECT DISTINCT city FROM patients;",
    ],
    solution: "SELECT DISTINCT city FROM patients;",
    explanation: "DISTINCT collapses duplicate values in the result set down to one row each.",
    thoughtProcess: [
      "\"Unique cities\" is the signal word for DISTINCT.",
      "We only need the city column, so select just that.",
    ],
    concept: "DISTINCT",
    tags: ["distinct"],
  },
  {
    id: "beg-03",
    level: "beginner",
    topic: "where",
    topicLabel: "WHERE",
    difficulty: "beginner",
    title: "Patients from Toronto",
    description: "Find all patients who live in the city of 'Toronto'. Return all their columns.",
    dataset: "healthcare",
    tables: ["patients"],
    hints: [
      "Filter rows with a WHERE clause.",
      "Compare the city column to the string 'Toronto'.",
      "SELECT * FROM patients WHERE city = 'Toronto';",
    ],
    solution: "SELECT * FROM patients WHERE city = 'Toronto';",
    explanation: "WHERE filters rows before they're returned, based on a boolean condition.",
    thoughtProcess: ["\"Who live in Toronto\" → WHERE city = 'Toronto'."],
    concept: "WHERE filtering",
    tags: ["where"],
  },
  {
    id: "beg-04",
    level: "beginner",
    topic: "logical-operators",
    topicLabel: "AND / OR",
    difficulty: "easy",
    title: "Toronto patients, male or born after 2005",
    description:
      "Find patients who live in 'Toronto' AND (are male OR were born after '2005-01-01'). Return patient_id, first_name, last_name, gender, birth_date.",
    dataset: "healthcare",
    tables: ["patients"],
    hints: [
      "You'll need AND to combine the city condition with the rest.",
      "Use OR between the gender condition and the birth_date condition, wrapped in parentheses.",
      "WHERE city = 'Toronto' AND (gender = 'M' OR birth_date > '2005-01-01')",
    ],
    solution:
      "SELECT patient_id, first_name, last_name, gender, birth_date FROM patients WHERE city = 'Toronto' AND (gender = 'M' OR birth_date > DATE '2005-01-01');",
    explanation: "Parentheses control operator precedence — without them AND binds tighter than OR and changes the meaning.",
    thoughtProcess: [
      "\"AND\" tells us city is a hard requirement.",
      "\"male OR born after 2005\" is a sub-condition, so it needs parentheses.",
    ],
    concept: "Combining AND / OR safely",
    tags: ["and", "or", "logical-operators"],
  },
  {
    id: "beg-05",
    level: "beginner",
    topic: "in",
    topicLabel: "IN",
    difficulty: "beginner",
    title: "Doctors in two specialties",
    description: "Find all doctors whose specialty is 'Cardiology' or 'Pediatrics' using IN.",
    dataset: "healthcare",
    tables: ["doctors"],
    hints: [
      "IN lets you match against a list of values instead of chaining OR.",
      "The column to check is specialty.",
      "WHERE specialty IN ('Cardiology', 'Pediatrics')",
    ],
    solution: "SELECT * FROM doctors WHERE specialty IN ('Cardiology', 'Pediatrics');",
    explanation: "IN is shorthand for multiple OR comparisons against the same column.",
    thoughtProcess: ["Two allowed values for one column → IN is cleaner than OR OR."],
    concept: "IN operator",
    tags: ["in"],
    requiresPattern: { regex: "\\bIN\\s*\\(", message: "Try using the IN (...) operator for this exercise." },
  },
  {
    id: "beg-06",
    level: "beginner",
    topic: "not-in",
    topicLabel: "NOT IN",
    difficulty: "easy",
    title: "Products outside Electronics and Books",
    description: "List products that are NOT in the 'Electronics' (category_id 1) or 'Books' (category_id 3) categories.",
    dataset: "ecommerce",
    tables: ["products"],
    hints: [
      "NOT IN excludes rows matching any value in the list.",
      "Use the category_id column with values 1 and 3.",
      "WHERE category_id NOT IN (1, 3)",
    ],
    solution: "SELECT * FROM products WHERE category_id NOT IN (1, 3);",
    explanation: "NOT IN filters out any row whose value matches one of the listed values.",
    thoughtProcess: ["\"NOT in these categories\" maps directly to NOT IN (1, 3)."],
    concept: "NOT IN operator",
    tags: ["not-in"],
  },
  {
    id: "beg-07",
    level: "beginner",
    topic: "between",
    topicLabel: "BETWEEN",
    difficulty: "beginner",
    title: "Patients born in the 2000s",
    description: "Find patients born between '2000-01-01' and '2009-12-31' inclusive.",
    dataset: "healthcare",
    tables: ["patients"],
    hints: [
      "BETWEEN is inclusive of both endpoints.",
      "Apply it to birth_date.",
      "WHERE birth_date BETWEEN '2000-01-01' AND '2009-12-31'",
    ],
    solution: "SELECT * FROM patients WHERE birth_date BETWEEN DATE '2000-01-01' AND DATE '2009-12-31';",
    explanation: "BETWEEN x AND y is equivalent to col >= x AND col <= y.",
    thoughtProcess: ["A date range with clear start/end → BETWEEN."],
    concept: "BETWEEN",
    tags: ["between"],
  },
  {
    id: "beg-08",
    level: "beginner",
    topic: "like",
    topicLabel: "LIKE",
    difficulty: "beginner",
    title: "Last names starting with S",
    description: "Find patients whose last_name starts with the letter 'S'.",
    dataset: "healthcare",
    tables: ["patients"],
    hints: [
      "LIKE supports wildcard matching; % matches any sequence of characters.",
      "You want names that begin with 'S', so the % goes after the S.",
      "WHERE last_name LIKE 'S%'",
    ],
    solution: "SELECT * FROM patients WHERE last_name LIKE 'S%';",
    explanation: "'S%' matches any string starting with 'S' followed by zero or more characters.",
    thoughtProcess: ["\"Starts with\" is the classic LIKE 'X%' pattern."],
    concept: "LIKE pattern matching",
    tags: ["like"],
  },
  {
    id: "beg-09",
    level: "beginner",
    topic: "is-null",
    topicLabel: "IS NULL",
    difficulty: "beginner",
    title: "Patients with no recorded allergies",
    description: "Find all patients where the allergies column has not been recorded (is NULL).",
    dataset: "healthcare",
    tables: ["patients"],
    hints: [
      "You can't use = NULL — NULL requires special syntax.",
      "Use IS NULL to test for missing values.",
      "WHERE allergies IS NULL",
    ],
    solution: "SELECT * FROM patients WHERE allergies IS NULL;",
    explanation: "NULL represents 'unknown/absent' and can only be tested with IS NULL / IS NOT NULL.",
    thoughtProcess: ["Missing data → IS NULL, never = NULL."],
    concept: "NULL handling",
    tags: ["is-null"],
  },
  {
    id: "beg-10",
    level: "beginner",
    topic: "order-by-limit",
    topicLabel: "ORDER BY / LIMIT",
    difficulty: "beginner",
    title: "5 most expensive products",
    description: "Return the name and price of the 5 most expensive products, most expensive first.",
    dataset: "ecommerce",
    tables: ["products"],
    hints: [
      "Sort using ORDER BY on price.",
      "Descending order needs DESC.",
      "SELECT name, price FROM products ORDER BY price DESC LIMIT 5;",
    ],
    solution: "SELECT name, price FROM products ORDER BY price DESC LIMIT 5;",
    explanation: "ORDER BY price DESC sorts highest-to-lowest, and LIMIT 5 keeps only the top 5 rows.",
    thoughtProcess: ["\"Most expensive\" → DESC.", "\"5\" → LIMIT 5."],
    concept: "Sorting and limiting results",
    tags: ["order-by", "limit"],
    orderMatters: true,
  },
  {
    id: "beg-11",
    level: "beginner",
    topic: "aliases",
    topicLabel: "Aliases",
    difficulty: "beginner",
    title: "Friendly column names",
    description: "Select product name and price, but label the columns 'Product' and 'Price' in the output.",
    dataset: "ecommerce",
    tables: ["products"],
    hints: [
      "Use AS to rename a column in the output.",
      "You can alias more than one column in the same SELECT.",
      "SELECT name AS Product, price AS Price FROM products;",
    ],
    solution: "SELECT name AS \"Product\", price AS \"Price\" FROM products;",
    explanation: "Aliases (AS) rename columns in the result without changing the underlying table.",
    thoughtProcess: ["Renaming output columns → AS alias on each expression."],
    concept: "Column aliases",
    tags: ["aliases"],
  },
  {
    id: "beg-12",
    level: "beginner",
    topic: "string-functions",
    topicLabel: "String functions",
    difficulty: "easy",
    title: "Uppercase customer names with length",
    description: "For each customer, show their name in uppercase and the number of characters in their name.",
    dataset: "ecommerce",
    tables: ["customers"],
    hints: [
      "UPPER() converts text to uppercase.",
      "LENGTH() returns the number of characters in a string.",
      "SELECT UPPER(name), LENGTH(name) FROM customers;",
    ],
    solution: "SELECT UPPER(name) AS name_upper, LENGTH(name) AS name_length FROM customers;",
    explanation: "UPPER() and LENGTH() are common string functions available in virtually every SQL dialect.",
    thoughtProcess: ["\"Uppercase\" → UPPER().", "\"Number of characters\" → LENGTH()."],
    concept: "String functions",
    tags: ["string-functions"],
  },
  {
    id: "beg-13",
    level: "beginner",
    topic: "date-functions",
    topicLabel: "Date functions",
    difficulty: "easy",
    title: "Birth year of every patient",
    description: "Show each patient's first_name, last_name, and the year they were born (as a number).",
    dataset: "healthcare",
    tables: ["patients"],
    hints: [
      "DuckDB supports EXTRACT(YEAR FROM date_column).",
      "You could also use YEAR(date_column) — both work in DuckDB.",
      "SELECT first_name, last_name, EXTRACT(YEAR FROM birth_date) AS birth_year FROM patients;",
    ],
    solution: "SELECT first_name, last_name, EXTRACT(YEAR FROM birth_date) AS birth_year FROM patients;",
    explanation: "EXTRACT(YEAR FROM ...) pulls the year component out of a DATE value.",
    thoughtProcess: ["Need a piece of a date → EXTRACT (or YEAR())."],
    concept: "Date functions",
    tags: ["date-functions"],
  },
  {
    id: "beg-14",
    level: "beginner",
    topic: "aggregation",
    topicLabel: "COUNT",
    difficulty: "beginner",
    title: "Total number of orders",
    description: "Count how many rows exist in the orders table.",
    dataset: "ecommerce",
    tables: ["orders"],
    hints: [
      "COUNT(*) counts all rows.",
      "No GROUP BY is needed for a single overall total.",
      "SELECT COUNT(*) FROM orders;",
    ],
    solution: "SELECT COUNT(*) AS total_orders FROM orders;",
    explanation: "COUNT(*) is an aggregate function that returns the number of rows.",
    thoughtProcess: ["\"How many\" → COUNT(*)."],
    concept: "COUNT aggregate",
    tags: ["count", "aggregation"],
  },
  {
    id: "beg-15",
    level: "beginner",
    topic: "aggregation",
    topicLabel: "SUM / AVG",
    difficulty: "easy",
    title: "Revenue from delivered orders",
    description: "Find the total (SUM) and average (AVG) order total for orders with status 'delivered'.",
    dataset: "ecommerce",
    tables: ["orders"],
    hints: [
      "Filter first with WHERE status = 'delivered'.",
      "SUM() and AVG() can both appear in the same SELECT.",
      "SELECT SUM(total), AVG(total) FROM orders WHERE status = 'delivered';",
    ],
    solution: "SELECT SUM(total) AS total_revenue, AVG(total) AS avg_order_value FROM orders WHERE status = 'delivered';",
    explanation: "Aggregate functions collapse many rows into a single summary value; WHERE filters before the aggregation happens.",
    thoughtProcess: ["Filter to delivered orders, then aggregate."],
    concept: "SUM and AVG",
    tags: ["sum", "avg", "aggregation"],
  },
  {
    id: "beg-16",
    level: "beginner",
    topic: "aggregation",
    topicLabel: "MIN / MAX",
    difficulty: "easy",
    title: "Cheapest and priciest product per category",
    description: "For each category_id, show the minimum and maximum product price.",
    dataset: "ecommerce",
    tables: ["products"],
    hints: [
      "You need one row per category, so GROUP BY category_id.",
      "MIN() and MAX() can be combined with GROUP BY.",
      "SELECT category_id, MIN(price), MAX(price) FROM products GROUP BY category_id;",
    ],
    solution: "SELECT category_id, MIN(price) AS min_price, MAX(price) AS max_price FROM products GROUP BY category_id;",
    explanation: "GROUP BY splits rows into buckets (one per category_id); MIN/MAX are computed within each bucket.",
    thoughtProcess: ["\"Per category\" → GROUP BY category_id."],
    concept: "GROUP BY with MIN/MAX",
    tags: ["min", "max", "group-by"],
  },
  {
    id: "beg-17",
    level: "beginner",
    topic: "group-by",
    topicLabel: "GROUP BY",
    difficulty: "beginner",
    title: "Patients per city",
    description: "Count how many patients live in each city.",
    dataset: "healthcare",
    tables: ["patients"],
    hints: [
      "Group rows by the city column.",
      "COUNT(*) inside each group counts the patients in that city.",
      "SELECT city, COUNT(*) FROM patients GROUP BY city;",
    ],
    solution: "SELECT city, COUNT(*) AS patient_count FROM patients GROUP BY city;",
    explanation: "GROUP BY city creates one group per distinct city; COUNT(*) counts rows within each group.",
    thoughtProcess: ["\"Per city\" is the GROUP BY signal."],
    concept: "GROUP BY",
    tags: ["group-by"],
  },
  {
    id: "beg-18",
    level: "beginner",
    topic: "having",
    topicLabel: "HAVING",
    difficulty: "easy",
    title: "Cities with more than 2 patients",
    description: "Find cities that have more than 2 patients registered.",
    dataset: "healthcare",
    tables: ["patients"],
    hints: [
      "WHERE can't filter on an aggregate like COUNT(*) — use HAVING instead.",
      "Group by city first, then filter groups.",
      "SELECT city, COUNT(*) FROM patients GROUP BY city HAVING COUNT(*) > 2;",
    ],
    solution: "SELECT city, COUNT(*) AS patient_count FROM patients GROUP BY city HAVING COUNT(*) > 2;",
    explanation: "HAVING filters groups after aggregation, while WHERE filters individual rows before aggregation.",
    thoughtProcess: ["Filtering on a group total → HAVING, not WHERE."],
    concept: "HAVING clause",
    tags: ["having", "group-by"],
  },
  {
    id: "beg-19",
    level: "beginner",
    topic: "having",
    topicLabel: "GROUP BY / HAVING",
    difficulty: "medium",
    title: "First names used exactly once",
    description: "Find first names among employees that appear exactly once (i.e. are unique in the table).",
    dataset: "company",
    tables: ["employees"],
    hints: [
      "Group by first_name and count occurrences.",
      "HAVING COUNT(*) = 1 keeps only names that appear once.",
      "SELECT first_name, COUNT(*) FROM employees GROUP BY first_name HAVING COUNT(*) = 1;",
    ],
    solution: "SELECT first_name FROM employees GROUP BY first_name HAVING COUNT(*) = 1;",
    explanation: "Grouping by the name and requiring a count of exactly one isolates values that don't repeat.",
    thoughtProcess: ["\"Occur only once\" → GROUP BY + HAVING COUNT(*) = 1."],
    concept: "HAVING with exact counts",
    tags: ["having", "group-by"],
  },
  {
    id: "beg-20",
    level: "beginner",
    topic: "where",
    topicLabel: "WHERE + Aliases",
    difficulty: "easy",
    title: "Affordable sports products",
    description: "Show the name and price (aliased as 'price_usd') of products in category_id 4 (Sports) priced under 30.",
    dataset: "ecommerce",
    tables: ["products"],
    hints: [
      "Combine two conditions on category_id and price with AND.",
      "Alias the price column in the SELECT list.",
      "SELECT name, price AS price_usd FROM products WHERE category_id = 4 AND price < 30;",
    ],
    solution: "SELECT name, price AS price_usd FROM products WHERE category_id = 4 AND price < 30;",
    explanation: "Two WHERE conditions joined with AND both must be true for a row to be returned.",
    thoughtProcess: ["Two filters, both required → AND."],
    concept: "WHERE + aliases combined",
    tags: ["where", "aliases"],
  },
];
