import type { Question } from "../types";

export const intermediateQuestions: Question[] = [
  {
    id: "int-01",
    level: "intermediate",
    topic: "joins",
    topicLabel: "INNER JOIN",
    difficulty: "easy",
    title: "Admissions with patient names",
    description: "Show admission_id, diagnosis, and the patient's first and last name for every admission.",
    dataset: "healthcare",
    tables: ["admissions", "patients"],
    hints: [
      "You need columns from two tables, so JOIN them.",
      "Match rows where admissions.patient_id equals patients.patient_id.",
      "SELECT a.admission_id, a.diagnosis, p.first_name, p.last_name FROM admissions a JOIN patients p ON a.patient_id = p.patient_id;",
    ],
    solution:
      "SELECT a.admission_id, a.diagnosis, p.first_name, p.last_name FROM admissions a JOIN patients p ON a.patient_id = p.patient_id;",
    explanation: "An INNER JOIN returns only rows that have a match in both tables, linked via the shared patient_id.",
    thoughtProcess: ["Need data spread across two tables → JOIN on the foreign key patient_id."],
    concept: "INNER JOIN",
    tags: ["inner-join"],
    requiresPattern: { regex: "\\bJOIN\\b", message: "Use a JOIN to combine admissions and patients." },
  },
  {
    id: "int-02",
    level: "intermediate",
    topic: "joins",
    topicLabel: "LEFT JOIN",
    difficulty: "medium",
    title: "Customers who never placed an order",
    description: "Find customers who have never placed any order. Return their id and name.",
    dataset: "ecommerce",
    tables: ["customers", "orders"],
    hints: [
      "LEFT JOIN keeps all customers, even those without a matching order.",
      "Rows with no matching order will have NULL in the orders columns.",
      "SELECT c.id, c.name FROM customers c LEFT JOIN orders o ON c.id = o.customer_id WHERE o.id IS NULL;",
    ],
    solution:
      "SELECT c.id, c.name FROM customers c LEFT JOIN orders o ON c.id = o.customer_id WHERE o.id IS NULL;",
    explanation: "LEFT JOIN + WHERE ... IS NULL is the classic pattern for finding rows on the left with no match on the right.",
    thoughtProcess: [
      "\"Never placed an order\" → all customers minus those who have a match in orders.",
      "LEFT JOIN customers to orders, then keep rows where the order side is NULL.",
    ],
    concept: "LEFT JOIN anti-pattern",
    tags: ["left-join"],
    requiresPattern: { regex: "LEFT\\s+JOIN", message: "Use a LEFT JOIN from customers to orders." },
  },
  {
    id: "int-03",
    level: "intermediate",
    topic: "joins",
    topicLabel: "Multi-table JOIN",
    difficulty: "medium",
    title: "Order items with product and category names",
    description: "For every order item, show the order_id, product name, category name, quantity and the item price.",
    dataset: "ecommerce",
    tables: ["order_items", "products", "categories"],
    hints: [
      "You'll need to join three tables total.",
      "order_items → products via product_id, products → categories via category_id.",
      "SELECT oi.order_id, p.name, c.name, oi.quantity, oi.price FROM order_items oi JOIN products p ON oi.product_id = p.id JOIN categories c ON p.category_id = c.id;",
    ],
    solution:
      "SELECT oi.order_id, p.name AS product_name, c.name AS category_name, oi.quantity, oi.price FROM order_items oi JOIN products p ON oi.product_id = p.id JOIN categories c ON p.category_id = c.id;",
    explanation: "Chaining JOINs lets you pull related columns across more than two tables in one query.",
    thoughtProcess: ["Three tables of related data → two JOIN clauses chained together."],
    concept: "Multi-table joins",
    tags: ["joins", "multi-join"],
  },
  {
    id: "int-04",
    level: "intermediate",
    topic: "set-operators",
    topicLabel: "UNION",
    difficulty: "easy",
    title: "All cities from patients and hospitals",
    description: "Return a single distinct list of every city that appears in either patients or hospitals.",
    dataset: "healthcare",
    tables: ["patients", "hospitals"],
    hints: [
      "UNION combines two result sets and removes duplicates automatically.",
      "Both SELECTs need the same number of columns.",
      "SELECT city FROM patients UNION SELECT city FROM hospitals;",
    ],
    solution: "SELECT city FROM patients UNION SELECT city FROM hospitals;",
    explanation: "UNION stacks two compatible result sets and de-duplicates the combined rows.",
    thoughtProcess: ["Combine two lists of the same shape, no duplicates → UNION."],
    concept: "UNION",
    tags: ["union"],
  },
  {
    id: "int-05",
    level: "intermediate",
    topic: "set-operators",
    topicLabel: "UNION ALL",
    difficulty: "easy",
    title: "Every first name, keeping duplicates",
    description: "Return first names from both patients and doctors in one list, keeping duplicates (don't remove them).",
    dataset: "healthcare",
    tables: ["patients", "doctors"],
    hints: [
      "UNION removes duplicates; UNION ALL keeps every row.",
      "Since we want duplicates preserved, use UNION ALL.",
      "SELECT first_name FROM patients UNION ALL SELECT first_name FROM doctors;",
    ],
    solution: "SELECT first_name FROM patients UNION ALL SELECT first_name FROM doctors;",
    explanation: "UNION ALL is faster than UNION because it skips the duplicate-elimination step.",
    thoughtProcess: ["\"Keeping duplicates\" is the explicit signal for UNION ALL over UNION."],
    concept: "UNION ALL",
    tags: ["union-all"],
    requiresPattern: { regex: "UNION\\s+ALL", message: "Use UNION ALL, not plain UNION, to keep duplicate rows." },
  },
  {
    id: "int-06",
    level: "intermediate",
    topic: "set-operators",
    topicLabel: "INTERSECT",
    difficulty: "medium",
    title: "Departments that have both a manager-less employee and someone with a manager",
    description:
      "Using INTERSECT, find dept_id values that appear both among employees with manager_id IS NULL and among employees with manager_id IS NOT NULL.",
    dataset: "company",
    tables: ["employees"],
    hints: [
      "Write two SELECTs: one for dept_id where manager_id IS NULL, one where it IS NOT NULL.",
      "INTERSECT keeps only rows present in both result sets.",
      "SELECT dept_id FROM employees WHERE manager_id IS NULL INTERSECT SELECT dept_id FROM employees WHERE manager_id IS NOT NULL;",
    ],
    solution:
      "SELECT dept_id FROM employees WHERE manager_id IS NULL INTERSECT SELECT dept_id FROM employees WHERE manager_id IS NOT NULL;",
    explanation: "INTERSECT returns only the rows that show up in both queries — useful for finding overlap between two sets.",
    thoughtProcess: ["\"Appear in both\" is exactly what INTERSECT computes."],
    concept: "INTERSECT",
    tags: ["intersect"],
    requiresPattern: { regex: "INTERSECT", message: "Use the INTERSECT set operator." },
  },
  {
    id: "int-07",
    level: "intermediate",
    topic: "subqueries",
    topicLabel: "IN subquery",
    difficulty: "medium",
    title: "Customers who have placed at least one order (IN subquery)",
    description: "Using an IN subquery (not a JOIN), find customers who have placed at least one order.",
    dataset: "ecommerce",
    tables: ["customers", "orders"],
    hints: [
      "A subquery in the WHERE clause can return a list of customer_ids from orders.",
      "Use IN to check membership in that list.",
      "SELECT * FROM customers WHERE id IN (SELECT customer_id FROM orders);",
    ],
    solution: "SELECT * FROM customers WHERE id IN (SELECT customer_id FROM orders);",
    explanation: "The subquery runs first, producing a list of customer_ids; the outer query keeps customers whose id is in that list.",
    thoughtProcess: ["\"At least one order\" + explicitly asked for IN subquery → WHERE id IN (SELECT ...)."],
    concept: "IN subquery",
    tags: ["subquery", "in"],
    requiresPattern: { regex: "IN\\s*\\(\\s*SELECT", message: "Use an IN (SELECT ...) subquery rather than a JOIN." },
  },
  {
    id: "int-08",
    level: "intermediate",
    topic: "subqueries",
    topicLabel: "EXISTS",
    difficulty: "medium",
    title: "Doctors who have admitted at least one patient",
    description: "Using EXISTS, find doctors who have at least one admission recorded.",
    dataset: "healthcare",
    tables: ["doctors", "admissions"],
    hints: [
      "EXISTS checks whether a correlated subquery returns any rows.",
      "Correlate the subquery on doctor_id.",
      "SELECT * FROM doctors d WHERE EXISTS (SELECT 1 FROM admissions a WHERE a.doctor_id = d.doctor_id);",
    ],
    solution:
      "SELECT * FROM doctors d WHERE EXISTS (SELECT 1 FROM admissions a WHERE a.doctor_id = d.doctor_id);",
    explanation: "EXISTS stops as soon as it finds one matching row, making it an efficient way to test for 'at least one'.",
    thoughtProcess: ["\"At least one admission\" + EXISTS keyword required → correlated EXISTS subquery."],
    concept: "EXISTS",
    tags: ["exists", "correlated-subquery"],
    requiresPattern: { regex: "EXISTS", message: "Use an EXISTS subquery." },
  },
  {
    id: "int-09",
    level: "intermediate",
    topic: "subqueries",
    topicLabel: "NOT EXISTS",
    difficulty: "medium",
    title: "Departments with no employees",
    description: "Using NOT EXISTS, find departments that currently have zero employees.",
    dataset: "company",
    tables: ["departments", "employees"],
    hints: [
      "NOT EXISTS is the negation of EXISTS — true when the subquery finds no matching rows.",
      "Correlate on dept_id between departments and employees.",
      "SELECT * FROM departments d WHERE NOT EXISTS (SELECT 1 FROM employees e WHERE e.dept_id = d.dept_id);",
    ],
    solution:
      "SELECT * FROM departments d WHERE NOT EXISTS (SELECT 1 FROM employees e WHERE e.dept_id = d.dept_id);",
    explanation: "NOT EXISTS is generally the safest way to express 'has none of these', avoiding NULL pitfalls that NOT IN can have.",
    thoughtProcess: ["\"Zero employees\" → invert EXISTS to NOT EXISTS."],
    concept: "NOT EXISTS",
    tags: ["not-exists", "correlated-subquery"],
    requiresPattern: { regex: "NOT\\s+EXISTS", message: "Use a NOT EXISTS subquery." },
  },
  {
    id: "int-10",
    level: "intermediate",
    topic: "case",
    topicLabel: "CASE",
    difficulty: "easy",
    title: "Label order sizes",
    description:
      "For each order, show its id, total, and a label: 'small' if total < 40, 'medium' if total is between 40 and 100, otherwise 'large'.",
    dataset: "ecommerce",
    tables: ["orders"],
    hints: [
      "CASE WHEN ... THEN ... lets you branch on conditions inline.",
      "List conditions in order from most specific to the catch-all ELSE.",
      "SELECT id, total, CASE WHEN total < 40 THEN 'small' WHEN total <= 100 THEN 'medium' ELSE 'large' END AS size_label FROM orders;",
    ],
    solution:
      "SELECT id, total, CASE WHEN total < 40 THEN 'small' WHEN total <= 100 THEN 'medium' ELSE 'large' END AS size_label FROM orders;",
    explanation: "CASE evaluates its WHEN branches top to bottom and returns the first matching THEN value.",
    thoughtProcess: ["Multiple labeled ranges on one column → CASE WHEN chain."],
    concept: "CASE expressions",
    tags: ["case"],
    requiresPattern: { regex: "CASE\\s+WHEN", message: "Use a CASE WHEN expression." },
  },
  {
    id: "int-11",
    level: "intermediate",
    topic: "null-handling",
    topicLabel: "COALESCE",
    difficulty: "easy",
    title: "Default text for missing allergies",
    description: "Show each patient's name and their allergies, replacing NULL allergies with the text 'None recorded'.",
    dataset: "healthcare",
    tables: ["patients"],
    hints: [
      "COALESCE returns the first non-NULL value from a list of expressions.",
      "COALESCE(allergies, 'None recorded') swaps in the fallback only when allergies is NULL.",
      "SELECT first_name, last_name, COALESCE(allergies, 'None recorded') FROM patients;",
    ],
    solution:
      "SELECT first_name, last_name, COALESCE(allergies, 'None recorded') AS allergies FROM patients;",
    explanation: "COALESCE is the standard SQL way to substitute a default value for NULLs.",
    thoughtProcess: ["\"Replace NULL with a default\" is exactly what COALESCE does."],
    concept: "COALESCE",
    tags: ["coalesce", "null-handling"],
    requiresPattern: { regex: "COALESCE", message: "Use COALESCE to substitute a default for NULL." },
  },
  {
    id: "int-12",
    level: "intermediate",
    topic: "aggregation",
    topicLabel: "Aggregates with JOIN",
    difficulty: "medium",
    title: "Total spent per customer",
    description: "For each customer, show their name and the total amount they've spent across all their orders (0 if none).",
    dataset: "ecommerce",
    tables: ["customers", "orders"],
    hints: [
      "LEFT JOIN customers to orders so customers with no orders are still included.",
      "SUM(total) will be NULL for customers with no matching rows — wrap it in COALESCE.",
      "SELECT c.name, COALESCE(SUM(o.total),0) FROM customers c LEFT JOIN orders o ON c.id = o.customer_id GROUP BY c.name;",
    ],
    solution:
      "SELECT c.id, c.name, COALESCE(SUM(o.total), 0) AS total_spent FROM customers c LEFT JOIN orders o ON c.id = o.customer_id GROUP BY c.id, c.name;",
    explanation: "LEFT JOIN keeps customers with zero orders; COALESCE turns their NULL sum into 0.",
    thoughtProcess: [
      "\"Every customer, including those with none\" → LEFT JOIN, not INNER JOIN.",
      "SUM per customer → GROUP BY customer.",
    ],
    concept: "Aggregation across a LEFT JOIN",
    tags: ["aggregation", "left-join"],
  },
  {
    id: "int-13",
    level: "intermediate",
    topic: "correlated-subquery",
    topicLabel: "Correlated subquery",
    difficulty: "hard",
    title: "Employees earning above their department's average",
    description: "Find employees whose salary is greater than the average salary of their own department.",
    dataset: "company",
    tables: ["employees"],
    hints: [
      "You need a per-employee comparison against a per-department average — this is a correlated subquery.",
      "The subquery re-runs for every outer row, filtered to the same dept_id.",
      "SELECT * FROM employees e WHERE salary > (SELECT AVG(salary) FROM employees e2 WHERE e2.dept_id = e.dept_id);",
    ],
    solution:
      "SELECT * FROM employees e WHERE salary > (SELECT AVG(e2.salary) FROM employees e2 WHERE e2.dept_id = e.dept_id);",
    explanation: "The inner query references the outer row's dept_id, so it recalculates a fresh average for each employee's department.",
    thoughtProcess: [
      "\"Their own department\" means the comparison value depends on the outer row → correlated subquery.",
    ],
    concept: "Correlated subqueries",
    tags: ["correlated-subquery"],
  },
  {
    id: "int-14",
    level: "intermediate",
    topic: "cte",
    topicLabel: "Common Table Expressions",
    difficulty: "medium",
    title: "Departments above average department size (CTE)",
    description: "Using a CTE, first compute the employee count per department, then return departments with more than 4 employees.",
    dataset: "company",
    tables: ["employees", "departments"],
    hints: [
      "WITH name AS (subquery) defines a CTE you can reference like a table.",
      "Build the per-department counts in the CTE, then filter in the outer query.",
      "WITH dept_counts AS (SELECT dept_id, COUNT(*) AS n FROM employees GROUP BY dept_id) SELECT * FROM dept_counts WHERE n > 4;",
    ],
    solution:
      "WITH dept_counts AS (SELECT dept_id, COUNT(*) AS n FROM employees GROUP BY dept_id) SELECT dept_id, n FROM dept_counts WHERE n > 4;",
    explanation: "A CTE names an intermediate result so the final query can filter or join against it cleanly, instead of nesting subqueries.",
    thoughtProcess: ["Two logical steps (aggregate, then filter) → a CTE keeps each step readable."],
    concept: "CTEs (WITH clause)",
    tags: ["cte"],
    requiresPattern: { regex: "WITH\\s+\\w+\\s+AS", message: "Use a WITH ... AS (...) common table expression." },
  },
  {
    id: "int-15",
    level: "intermediate",
    topic: "string-functions",
    topicLabel: "String manipulation",
    difficulty: "easy",
    title: "Full name and email domain",
    description: "For each customer, show a full_name (name as-is) and the domain portion of their email (everything after the @).",
    dataset: "ecommerce",
    tables: ["customers"],
    hints: [
      "SUBSTRING and POSITION (or STRPOS) can extract text after a character.",
      "DuckDB's STRPOS(email, '@') gives you the position of '@'.",
      "SELECT name, SUBSTRING(email FROM POSITION('@' IN email) + 1) FROM customers;",
    ],
    solution:
      "SELECT name AS full_name, SUBSTRING(email FROM POSITION('@' IN email) + 1) AS email_domain FROM customers;",
    explanation: "POSITION locates the '@' character, and SUBSTRING(... FROM n) returns everything from that position onward.",
    thoughtProcess: ["Extracting the part after a delimiter → find the delimiter's position, then substring from there."],
    concept: "String manipulation",
    tags: ["string-functions"],
  },
  {
    id: "int-16",
    level: "intermediate",
    topic: "date-functions",
    topicLabel: "Date calculations",
    difficulty: "medium",
    title: "Length of hospital stay",
    description: "For admissions with a discharge_date, show admission_id and the number of days between admission_date and discharge_date.",
    dataset: "healthcare",
    tables: ["admissions"],
    hints: [
      "Only include rows where discharge_date IS NOT NULL.",
      "Subtracting one DATE from another in DuckDB gives a number of days.",
      "SELECT admission_id, discharge_date - admission_date AS days_stayed FROM admissions WHERE discharge_date IS NOT NULL;",
    ],
    solution:
      "SELECT admission_id, (discharge_date - admission_date) AS days_stayed FROM admissions WHERE discharge_date IS NOT NULL;",
    explanation: "DuckDB supports direct DATE subtraction, returning the difference in days.",
    thoughtProcess: ["A duration between two dates → subtract them directly."],
    concept: "Date arithmetic",
    tags: ["date-functions"],
  },
  {
    id: "int-17",
    level: "intermediate",
    topic: "subqueries",
    topicLabel: "Correlated subquery",
    difficulty: "hard",
    title: "Patients admitted more than once for the same diagnosis",
    description: "Find patients (by patient_id) who have two or more admissions that share the exact same diagnosis.",
    dataset: "healthcare",
    tables: ["admissions"],
    hints: [
      "Group admissions by patient_id and diagnosis together.",
      "HAVING COUNT(*) >= 2 keeps only repeated combinations.",
      "SELECT patient_id, diagnosis, COUNT(*) FROM admissions GROUP BY patient_id, diagnosis HAVING COUNT(*) >= 2;",
    ],
    solution:
      "SELECT patient_id, diagnosis, COUNT(*) AS times FROM admissions GROUP BY patient_id, diagnosis HAVING COUNT(*) >= 2;",
    explanation: "Grouping by two columns together treats each (patient, diagnosis) pair as its own bucket, which HAVING can then filter.",
    thoughtProcess: ["\"Same diagnosis, more than once\" → GROUP BY (patient_id, diagnosis) + HAVING COUNT >= 2."],
    concept: "Multi-column GROUP BY",
    tags: ["group-by", "having"],
  },
  {
    id: "int-18",
    level: "intermediate",
    topic: "joins",
    topicLabel: "RIGHT JOIN",
    difficulty: "medium",
    title: "All doctors, with hospital name if known",
    description: "Using a RIGHT JOIN (hospitals RIGHT JOIN doctors), show every doctor's name alongside their hospital's name.",
    dataset: "healthcare",
    tables: ["doctors", "hospitals"],
    hints: [
      "RIGHT JOIN keeps every row from the right-hand table, matching where possible.",
      "Write hospitals RIGHT JOIN doctors so all doctors are preserved.",
      "SELECT d.first_name, d.last_name, h.hospital_name FROM hospitals h RIGHT JOIN doctors d ON h.hospital_id = d.hospital_id;",
    ],
    solution:
      "SELECT d.first_name, d.last_name, h.hospital_name FROM hospitals h RIGHT JOIN doctors d ON h.hospital_id = d.hospital_id;",
    explanation: "A RIGHT JOIN is a LEFT JOIN with the table order flipped — it keeps all rows from the table on the right side of the keyword.",
    thoughtProcess: ["Every doctor must appear, hospital is the 'right' table → RIGHT JOIN keeps it symmetric with LEFT JOIN logic."],
    concept: "RIGHT JOIN",
    tags: ["right-join"],
    requiresPattern: { regex: "RIGHT\\s+JOIN", message: "Use a RIGHT JOIN as the exercise asks." },
  },
];
